repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: make isort
        types: [file, python]
        pass_filenames: false
        language: system

      - id: system
        name: black
        entry: make black
        types: [file, python]
        pass_filenames: false
        language: system

      - id: system
        name: autoflake
        entry: make autoflake
        types: [file, python]
        pass_filenames: false
        language: system

      - id: system
        name: mypy
        entry: make mypy
        types: [file, python]
        pass_filenames: false
        language: system

      - id: system
        name: flake8
        entry: make flake8
        types: [file, python]
        pass_filenames: false
        language: system
        
