version: "3.9"

services:
  jupyter:
    build:
      context: "."
      target: "development"
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/usr/src/notebooks"
    env_file: ".env"
  scripts:
    build:
      context: "."
      target: "test"
    volumes:
      - ".:/usr/src/scripts"
    env_file: ".env"

networks:
  default:
    name: mlflow
    external: true
